import * as React from "react";
import { View, Text, StyleSheet, Image, Button } from "react-native";
import { useState } from "react";
import Header from "../components/Header";
import * as ImagePicker from "expo-image-picker";
function Home() {
  const [image, setImage] = useState(null);

  const pickImage = async () => {
    // No permissions request is necessary for launching the image library
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.All,
      allowsEditing: false,
      aspect: [1, 1],
      quality: 1,
    });

    console.log(result);

    if (!result.canceled) {
      setImage(result.assets[0].uri);
    }
  };

  return (
    <View style={styles.wrapper}>
      <Header />
      <View style={styles.container}>
        {image && <Image source={{ uri: image }} style={styles.image} />}
        <Button
          style={styles.button}
          title="Upload Image"
          onPress={pickImage}
        />
      </View>

      <Text style={styles.prediction}>Prediction : Gay</Text>
      <View style={styles.bottombox}>
        <Text style={styles.bottomtext}>
          This output is generated by a machine learning model with an 85%
          accuracy rate.
        </Text>
        <Text style={styles.bottomtext}>
          For a definitive diagnosis, it is recommended to consult a
          dermatologist.
        </Text>
      </View>
    </View>
  );
}

export default Home;

const styles = StyleSheet.create({
  wrapper: {
    height: "100%",
    backgroundColor: "beige",
  },
  container: {
    marginTop: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  image: {
    width: 200,
    height: 200,
    margin: 10,
    borderWidth: 3,
    borderColor: "green",
  },
  button: {
    width: 1000,
    margin: 10,
  },
  prediction: {
    margin: 10,
    fontWeight: "bold",
    fontSize: 20,
    textAlign: "center",
  },
  bottomtext:{
    textAlign:'center',
    color:'red',
    fontWeight:'bold',
  },
  bottombox: {
    width:'100%',
    backgroundColor:'black',
    padding:10,
    position: "absolute",
    bottom: 0,
  },
});
